import React from 'react';
import Head from 'next/head';
import Image from 'next/future/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { motion } from 'framer-motion';

import data from '../data.json';

import NavBar from '../components/NavBar';
import HeroTitle from '../components/HeroTitle';
import HeroImage from '../components/HeroImage';
import Skills from '../components/Skills';
import ProyectsList from '../components/ProyectsList';
import FooterAndContact from '../components/FooterAndContact';

import { IoLogoGithub, IoGlobe, IoCheckmarkCircleOutline } from 'react-icons/io5'; 

export default function ProyectModal() {
  const router = useRouter();
  const { proyectId } = router.query;
  
  const proyect = data.proyects.find(proyect => proyect.id === proyectId);

  if ( 
    data.proyects.findIndex( proyect => proyect.id === proyectId ) === -1
   ) return <div className='text-black'>Proyect not found</div>


  console.log( data.proyects.find( proyect => proyect.id === proyectId ) || null );


  return (
    <div className="">
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/line.svg" />
    </Head>

    <main className="w-full h-screen p-0 m-0">      

      <NavBar />

      
      <motion.div class="flex flex-col w-full bg-white" id="ProyectsList"
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}>
            <div class="flex flex-col items-center justify-center px-5 mx-auto lg:w-11/12 lg:px-10 md:flex-row py-12">
            <div class="basis-full flex flex-col items-center justify-center text-center lg:flex-grow md:flex md:flex-col md:justify-center">
                <div class="relative flex flex-col w-full items-center">
                  

                  <div class="grid w-full grid-cols-1 items-start gap-y-8 gap-x-6 sm:grid-cols-12 lg:gap-x-8 lg:py-10 sm:px-6 sm:pt-8 md:p-6 lg:p-8">
                    <div class="sm:col-span-12 lg:col-span-8">
                      <motion.h2 
                        class="text-7xl font-bold text-palette-500 sm:pr-12 text-left"
                        // layoutId={ "ProyectTitle-" + proyect.id}
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        >
                        { proyect.name }{ proyect.name }{ proyect.name }
                      </motion.h2>

                      {/* here goes the status of the proyect */}
                      <motion.div
                        initial={{ opacity:0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.5 }}
                        class="flex justify-start pt-5 pb-0">
                        <span class={`inline-block rounded-sm px-3 py-1 text-sm font-semibold mr-2 mb-2 `}
                        style={{ backgroundColor: proyect.status.color }}
                        >
                          {proyect.status.text}
                        </span>
                      </motion.div>

                      <section aria-labelledby="information-heading" class="">
                        <h3 id="information-heading" class="sr-only">Proyects description</h3>
                        <motion.div
                          initial={{ opacity:0 }}
                          animate={{ opacity: 1 }}
                          transition={{ delay: 0.5 }}
                          class="mt-8 space-y-6">
                          <p class="text-lg font-medium text-gray-900 text-left">
                            { proyect.description }
                          </p>
                        </motion.div>
                        
                      </section>

                      {/* put links to github and the website if is deployed */}
                      <motion.div
                        initial={{ opacity:0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.5 }}
                        class="mt-12 flex flex-row justify-start ">
                        <a rel="noreferrer" href={proyect.github} target="_blank" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-palette-100 bg-gray-900 hover:bg-gray-700 hover:underline hover:cursor-pointer">
                          Go to Github repo 
                          <IoLogoGithub class="ml-2 h-5 w-5" aria-hidden="true" />
                        </a>

                        {
                          proyect.website || 
                          <a rel="noreferrer" href={proyect.website} target="_blank" class="ml-4 inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-palette-100 bg-gray-900 hover:bg-gray-700 hover:underline hover:cursor-pointer">
                            Website
                            <IoGlobe class="ml-2 h-5 w-5" aria-hidden="true" />
                          </a>
                        }
                      </motion.div>

                    </div>
                    <motion.div
                      initial={{ opacity:0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.5 }}
                      class="sm:col-span-12 lg:col-span-4 gap-y-2 flex flex-row flex-wrap justify-between">
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12 text-left">
                        Technologies
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            proyect.languages.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12 text-left">
                        Some libraries
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            proyect.libraries.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12 text-left">
                        Database and hosting
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            proyect.libraries.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>

                    </motion.div>

                    <motion.div 
                    class="w-full basis-full h-64 col-span-12" 
                    // layoutId={ "ProyectIMG-"}
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    exit={{ scale: 0.8, opacity: 0 }}
                  >
                    <Image
                      src="/donateloImg.png"
                      alt={proyect.title}
                      width={800}
                      height={200}
                      layout="fill"
                      className="object-cover object-center w-full h-64"
                      hover={{ scale: 1.1 }}
                    />
                  </motion.div>

                  </div>
                </div>
              </div>
            </div>
      </motion.div>


      
      
      <FooterAndContact />
      </main>
    </div>
  )
}
