import React, { useEffect, useState, useRef } from 'react';
import Head from 'next/head';
import Image from 'next/future/image';
import {motion} from 'framer-motion';

import data from '../data.json';


import { IoLogoJavascript, IoLogoNodejs, IoLogoGithub, IoLogoInstagram, IoLogoLinkedin, IoLogoReact, IoLogoDiscord, IoLogoHtml5, IoLogoCss3, IoChatboxEllipses, IoGlobe, IoCheckmarkCircleOutline } from 'react-icons/io5';
import { SiMongodb, SiNextdotjs } from 'react-icons/si';
import { GrMysql } from 'react-icons/gr';



// Callback for IntersectionObserver
const callback = function(entries) {
  entries.forEach(entry => {

    // Is the element in the viewport?
    if (entry.isIntersecting) {

      // Add the fadeIn class:
      entry.target.classList.add("motion-safe:animate-fadeIn");
    } else {

      // Otherwise remove the fadein class
      entry.target.classList.remove("motion-safe:animate-fadeIn");
    }
  });
};

const defaultProyect = {
  "name": "Proyecto 0",
  "description": "Descripción del proyecto 1Descripción del proyecto 1Descripción del proyecto 1grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3",
  "image": "dvsahkj",
  "languages": [
      "Java",
      "C#",
      "Python"
  ],
  "libraries": [
      "Spring",
      "Hibernate",
      "Django"
  ],
  "databases": [
      "MySQL",
      "PostgreSQL",
      "MongoDB"
  ],
  "status": "En proceso",
  "startDate": "2019-01-01",
  "endDate": "2019-12-31"
}

export default function Home() {

  const [selectedProject, setSelectedProject] = useState(defaultProyect);
  const [isModalOpen, setModalOpen] = useState(false);
  const [contactStatus, setContactStatus] = useState("default");
  const modalRef = useRef(null);

  // Create an observer instance
  useEffect(() => {
    // Get all the elements you want to show on scroll
    const targets = document.querySelectorAll(".show-on-scroll");

    // Set up a new observer
    const observer = new IntersectionObserver(callback);

    // Loop through each of the target
    targets.forEach(function(target) {
      // Hide the element
      target.classList.add("opacity-0");

      // Add the element to the watcher
      observer.observe(target);
    });

  }, []);

  const handleModalOpen = (index) => {
    setSelectedProject(data.proyects[index]);
    setTimeout(() => {
      setModalOpen(true);
    }, 500);
  }

  const handleModalExit = () => {
    setModalOpen(false);
    setTimeout(() => {
      setSelectedProject(defaultProyect);
    }, 500);
  }

  const handleContactMe = () => {
    //change the status to email with a delay
    setTimeout(() => {
      console.log("email sent");
      setContactStatus("email");
    }, 1800);

    //change the status to phone after 2 seconds
    setTimeout(() => {
      setContactStatus("phone");
    }, 4000);
  }

  const handleContactMeLeave = () => {
    setTimeout(() => {
      setContactStatus("default")
    }, 5000);
  }

  const handleCopyContact = () => {
    navigator.clipboard.writeText(
      contactStatus === "email" ? "512juanm@gmail.com" : "+5492346570764"
    );
    setContactStatus("copied");

    //change the status to phone after 2 seconds
    // setTimeout(() => {
    //   setContactStatus("phone");
    // }, 2000);
  }


  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/line.svg" />
      </Head>

      <main className="w-full h-screen p-0 m-0">      

        <nav class="bg-white border-gray-200 px-3 md:px-20 md:py-8 rounded dark:bg-gray-900">
          <div class="container flex flex-wrap justify-between items-center mx-auto">
            <div class="md:flex md:justify-center md:w-auto md:order-2 mt-8 mx-2 md:mt-0">
              {/* <h1 class="md:basis-1/3 text-xl font-bold text-palette-400 font-mono text-center">Juan Manuel Vila</h1> */}
              <div class="relative md:basis-1/3 text-xl font-bold text-palette-400 font-mono text-center ml-8">
                {/* <LogoSVG className="w-28 h-28 hidden md:block" />
                <LogoSVGsmall className="w-16 h-16 md:hidden" /> */}
                <i className='w-32 h-32'>{'</>'}</i>
                <svg className='absolute top-0 left-0 w-32 h-32 animate-[spin_10s_linear_infinite] ' 
                viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"
                style={{
                  left: "-145%",
                  top: "-170%"
                }}
                >
                  <path fill="none" id="curve" d="M 50 100 A 50 50 0 1 1 150 100 A 50 50 0 1 1 50 100 " />
                  <text width="500">
                    <textPath alignment-baseline="top" href="#curve" className=' underline font-bold'>
                      Juan Manuel Vila-FullStack 
                    </textPath>
                  </text>
                </svg>
              </div>
            </div>
            <div class="md:basis-1/3 flex justify-center mt-6 lg:flex lg:mt-0 md:order-3">
              <div className="hidden md:flex">
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Reddit">
                    <IoLogoGithub size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Facebook">
                    <IoLogoInstagram size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoLinkedin size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoDiscord size={25} />
                </a>
              </div>
                <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
              </button>
            </div>
            <div class="md:basis-1/3 hidden justify-center mt-6 md:flex md:mt-0 lg:-mx-2 md:order-1" id="navbar-cta">
              <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold border-b-2 md:rounded-none border-palette-400 text-white bg-palette-400 rounded md:bg-transparent md:text-palette-400 md:p-0 dark:text-white" aria-current="page">Home</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>




          <div class="flex flex-col items-center justify-center px-5 py-16 mx-auto lg:px-20 md:flex-row show-on-scroll">
              <h1 class="mb-4 text-3xl text-gray-900 lg:text-6xl md:text-3xl text-center font-normal ">
                Hi, I{"'"}m <span class="text-palette-400">Juan Manuel Vila</span> <br /><span class="text-palette-400">Full Stack Developer</span> <br class="hidden md:block" />from <span class="text-palette-400">Argentina</span>
              </h1>
          </div>



        <div class=" bg-white dark:bg-gray-900 show-on-scroll">
          <div class="flex flex-col items-center justify-center px-5 py-16 mx-auto lg:px-20 md:flex-row">
            
            <div class="order-2 md:order-1 basis-full md:basis-4/12 flex flex-col items-center justify-center text-center lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 md:items-start md:text-left md:flex md:flex-col md:justify-center">
              
              <div class="flex flex-col">
                <h4 class="mb-3 text-sm font-normal text-gray-900 uppercase"><span class="border-b-2 border-palette-400 text-palette-300">Biography</span></h4>
                <p class="mb-12 text-base font-normal text-gray-700 md:text-md font-amiri">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed ex ea commodo consequat.
                </p>
              </div>
              <div class="flex flex-col">
                <h4 class="mb-3 text-sm font-normal text-gray-900 uppercase"><span class="border-b-2 border-palette-400 text-palette-300">Contact</span></h4>
                <p class="mb-12 text-base font-normal text-gray-700 md:text-md font-amiri">
                  512juanm@gmail.com <br />
                  +54 9 2346-570764 <br />
                  La Plata, Buenos Aires, Argentina

                </p>
              </div>

              
            </div>

            {/* IMAGE */}
            <div class="basis-4/12 relative p-2 w-64 md:w-full order-1 md:order-2">
              <Image width="500" height="500" class="relative mx-auto z-10 object-cover object-center show-on-scroll delay-500" alt="hero" src="/heroIMG.jpg"
                style={
                  {
                    'border-top-left-radius': "12rem 12rem",
                    'border-top-right-radius': "12rem 12rem",
                    'border-bottom-right-radius': "12rem 12rem",
                    'border-bottom-left-radius': "12rem 12rem",
                    border: "10px solid #fefefe",
                    boxShadow: "0.1px 0.1px 1px 0.5px rgba(18, 164, 42, 0.4), -0.1px -0.1px 1px 0.5px rgba(18, 164, 42, 0.4)",
                  }
                }
              />
            </div>

            <div class="order-3 md:order-3 basis-4/12 relative text-center flex flex-col items-end justify-end lg:flex-grow md:w-full lg:pl-24 md:pl-16 md:items-end md:text-rigth md:flex md:flex-col md:justify-end">
              <div class="flex flex-col md:text-right w-full">
                <h4 class="mb-3 text-sm font-normal text-gray-900 uppercase"><span class=" text-palette-500">Currently<br/> Learning</span></h4>
                <p class="mb-12 text-3xl font-base text-gray-700 md:text-3xl font-amiri">
                  <span class="text-palette-400 block">Typescript</span> <span class="text-palette-400 block">Next.js</span>

                </p>
              </div>
              <div class="flex flex-col md:text-right w-full">
                <h4 class="mb-3 text-sm font-normal text-gray-900 uppercase"><span class=" text-palette-500">Working<br/> On</span></h4>
                <p class="mb-12 text-3xl font-base text-gray-700 md:text-3xl font-amiri">
                    <span class="text-palette-400 block">VaS-Ecommerce</span> <span class="text-palette-400 block">Portfolio</span> <span class="text-palette-400 block">UNO web-game</span>
                </p>
              </div>
              <div class="flex flex-col md:text-right w-full">
                <h4 class="mb-3 text-sm font-normal text-gray-900 uppercase"><span class=" text-palette-500">Proyects<br/> done</span></h4>
                <p class="mb-12 font-base text-gray-700 text-4xl md:text-5xl font-amiri">
                    <span class="text-palette-400 block">18</span>
                </p>
              </div>

            </div>

          </div>

          <div class="flex flex-row items-center justify-center px-5 py-16 mx-auto lg:px-20 gap-8 flex-wrap show-on-scroll delay-150">
            <Image width="200" height="200" class="relative mx-auto object-cover object-center transition-all duration-200 opacity-50 hover:opacity-100 hover:-translate-y-1 " alt="hero" src="/education/logo-informatica.png" />
            <Image width="250" height="250" class="relative mx-auto object-cover object-center transition-all duration-200 opacity-50 hover:opacity-100 hover:-translate-y-1 " alt="hero" src="/education/logo_facultad_ingenieria.png" />
            <Image width="200" height="200" class="relative mx-auto object-cover object-center transition-all duration-200 opacity-50 hover:opacity-100 hover:-translate-y-1 " alt="hero" src="/education/FreeCodeCamp_logo.png" />
            <Image width="200" height="200" class="relative mx-auto object-cover object-center transition-all duration-200 opacity-50 hover:opacity-100 hover:-translate-y-1 " alt="hero" src="/education/MDN_Web_Docs-Logo.svg" />
            <Image width="200" height="200" class="relative mx-auto object-cover object-center transition-all duration-200 opacity-50 hover:opacity-100 hover:-translate-y-1 " alt="hero" src="/education/W3Schools_logo.png" />
          </div>
        </div>

        <div class="flex flex-col w-full bg-white show-on-scroll">
          <div class="flex flex-col items-center justify-center px-5 mx-auto lg:w-11/12 lg:px-10 md:flex-row py-20 border-t border-gray-700">
            <div class="basis-full flex flex-col items-center justify-center text-center lg:flex-grow md:flex md:flex-col md:justify-center">
              <h1 class="my-4 text-2xl font-normal text-gray-900 md:text-5xl dark:text-white border-b-2 border-palette-400">My Knowledge</h1>
              <div class="flex flex-row justify-center gap-5 md:gap-12 flex-wrap py-20 show-on-scroll delay-300">

                <div class="flex flex-col items-center justify-center gap-0 ">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                    <IoLogoHtml5 size={55} color="#3178C6" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110' />
                    <p class="text-base font-semibold group-hover:text-[#3178C6] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">HTML</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoCss3 size={55} color="#264DE4" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#264DE4] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">CSS</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoJavascript size={55} color="#F7DF1E" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#F7DF1E] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">Javascript</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoReact size={55} color="#61DAFB" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#61DAFB] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">React</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoNodejs size={55} color="#339933" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#339933] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">NodeJS</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <SiNextdotjs size={55} color="#3776AB" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#3776AB] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">NextJS</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <GrMysql size={55} color="#4479A1" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#4479A1] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">MySQL</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 md:w-40 h-48 md:h-64 bg-gray-200 grayscale hover:grayscale-0 transition-all duration-500 hover:scale-110 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <SiMongodb size={55} color="#47A248" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#47A248] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">MongoDB</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Proyects */}
        <div class="flex flex-col w-full bg-white">
          <div class="flex flex-col items-center justify-center px-5 mx-auto lg:w-11/12 lg:px-10 md:flex-row py-20 border-t border-gray-700">
            <div class="basis-full flex flex-col items-center justify-center text-center lg:flex-grow md:flex md:flex-col md:justify-center">
              <h1 class="my-4 text-2xl font-normal text-gray-900 md:text-5xl border-b-2 border-palette-400">My Proyects</h1>
              
              <div class="grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3 py-20 show-on-scroll">
                {
                  data.proyects.map((proyect, index) => (
                    <div key={index} class={"group overflow-hidden transition-opacity hover:opacity-100 " + (selectedProject.name === proyect.name ? " opacity-0 duration-300" : " opacity-70 duration-200") }>
                      <motion.div onClick={ ()=> handleModalOpen(index) } class="object-cover w-full h-64 transition-all duration-100 " layoutId={proyect.id}>
                                <Image
                                    src="/donateloImg.png"
                                    alt={proyect.title} width={400} height={400}
                                    layout="fill"
                                    objectFit="cover"
                                    objectPosition="center"
                                    className="object-cover w-full h-64 transition-all duration-1000 transform group-hover:scale-110 grayscale group-hover:grayscale-0 cursor-pointer"
                                />
                      </motion.div>
                      <div class="flex justify-start  pt-8 pb-0">
                        {
                          proyect.languages.map( (lang, i ) =>(
                            <span key={i} class="inline-block bg-gray-200 rounded-sm px-3 py-1 text-sm font-semibold text-gray-700 transition-all duration-500  opacity-50 group-hover:opacity-100 delay-100 mr-2 mb-2">
                              {lang}
                            </span>
                          ))
                        } 
                      </div>
                      <div class=" py-2">
                        <button onClick={ ()=> handleModalOpen(index) } className="w-full flex justify-start" > 
                          <span class="text-left font-bold text-xl mb-2 text-gray-800 transition-all cursor-pointer duration-500 delay-100 hover:underline opacity-50 group-hover:opacity-100">
                            {proyect.name}
                          </span>
                        </button>
                        {/* <p class="text-gray-700 text-base h-24 overflow-y-hidden ">
                          {proyect.description}
                        </p>*/}
                      </div>

                    </div>

                  ))
                }
                
                
                
              </div>
            </div>
          </div>
        </div>

        {/* modal here */}
        {isModalOpen &&
        <section className={`relative z-10` + ( isModalOpen ? "" : " hidden")} >

          <div className={`fixed inset-0 z-20 bg-[#52525250] cursor-pointer`} onClick={ ()=> handleModalExit() }></div>

          <div class="fixed inset-0 left-[50%] -translate-x-[50%] z-50 overflow-y-auto w-full md:w-8/12 my-5">
            <div class="flex min-h-full w-full items-stretch justify-center text-center md:items-center">
              <div class="flex h-fit w-full transform text-left text-base transition md:my-0">
                <div class="relative flex flex-col w-full items-center overflow-hidden bg-white shadow-2xl">
                  <motion.div class="w-full basis-full h-64 " layoutId={selectedProject.id}>
                    <Image
                      src="/donateloImg.png"
                      alt={selectedProject.title}
                      width={800}
                      height={200}
                      layout="fill"
                      className="rounded-b-lg object-cover object-center w-full h-64"
                      hover={{ scale: 1.1 }}
                    />
                    <div class="mt-4">
                      <h3 class="text-lg font-medium text-gray-900">{selectedProject.title}</h3>
                    </div>
                  </motion.div>
                  <button onClick={ ()=> handleModalExit() } type="button" class="absolute top-0 right-0 bg-black rounded-full p-2 text-gray-200 hover:text-gray-500 sm:top-8 sm:right-6 md:top-6 md:right-6 lg:top-8 lg:right-8">
                    <span class="sr-only">Close</span>
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>


                  <div class="grid w-full grid-cols-1 items-start gap-y-8 gap-x-6 sm:grid-cols-12 lg:gap-x-8 lg:py-10 sm:px-6 sm:pt-8 md:p-6 lg:p-8">
                    {/* <div class="aspect-w-2 aspect-h-3 overflow-hidden rounded-lg bg-gray-100 sm:col-span-4 lg:col-span-5">
                      <img src="https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg" alt="Two each of gray, white, and black shirts arranged on table." class="object-cover object-center" />
                    </div> */}
                    <div class="sm:col-span-12 lg:col-span-8">
                      <h2 class="text-7xl font-bold text-palette-500 sm:pr-12">
                        { selectedProject.name }
                      </h2>

                      {/* here goes the status of the selectedProject */}
                      <div class="flex justify-start pt-5 pb-0">
                        <span class={`inline-block rounded-sm px-3 py-1 text-sm font-semibold mr-2 mb-2 `}
                        style={{ backgroundColor: selectedProject.status.color }}
                        >
                          {selectedProject.status.text}
                        </span>
                      </div>

                      <section aria-labelledby="information-heading" class="">
                        <h3 id="information-heading" class="sr-only">Proyects description</h3>
                        <div class="mt-8 space-y-6">
                          <p class="text-lg font-medium text-gray-900">
                            { selectedProject.description }
                          </p>
                        </div>
                        
                      </section>

                      {/* put links to github and the website if is deployed */}
                      <div class="mt-12 flex flex-row justify-start ">
                        <a rel="noreferrer" href={selectedProject.github} target="_blank" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-palette-100 bg-gray-900 hover:bg-gray-700 hover:underline hover:cursor-pointer">
                          Go to Github repo 
                          <IoLogoGithub class="ml-2 h-5 w-5" aria-hidden="true" />
                        </a>

                        {
                          selectedProject.website || 
                          <a rel="noreferrer" href={selectedProject.website} target="_blank" class="ml-4 inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-palette-100 bg-gray-900 hover:bg-gray-700 hover:underline hover:cursor-pointer">
                            Website
                            <IoGlobe class="ml-2 h-5 w-5" aria-hidden="true" />
                          </a>
                        }
                      </div>

                    </div>
                    <div class="sm:col-span-12 lg:col-span-4 gap-y-2 flex flex-row flex-wrap justify-between">
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12">
                        Technologies
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            selectedProject.languages.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12">
                        Some libraries
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            selectedProject.libraries.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12">
                        Database and hosting
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            selectedProject.libraries.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>

                    </div>



                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        }

        {/* <div className={`relative z-10` + ( isModalOpen ? "" : "hidden")}
        aria-labelledby="modal-title" role="dialog" aria-modal="true">

          <div className={`fixed inset-0 z-20 bg-[#52525210] cursor-pointer`}
          onClick={ ()=> handleModalExit() }
          aria-hidden="true"></div>

          <div ref={modalRef} class="fixed inset-0 left-[50%] -translate-x-[50%] z-50 overflow-y-auto w-full md:w-8/12">
          {/* <div ref={modalRef} class="fixed top-0 left-0 right-0 md:fixed md:top-[50%] md:left-[50%] md:-translate-y-[50%] md:-translate-x-[50%] z-50 overflow-y-auto w-full md:w-8/12 "> */}
            {/* <div class="flex min-h-full w-full items-stretch justify-center text-center md:items-center">
              <div class="flex h-fit w-full transform text-left text-base transition md:my-0">
                <div class="relative flex w-full items-center overflow-hidden bg-white px-4 pt-14 pb-8 shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
                  <button onClick={ ()=>handleModalExit() } type="button" class="absolute top-4 right-4 text-gray-400 hover:text-gray-500 sm:top-8 sm:right-6 md:top-6 md:right-6 lg:top-8 lg:right-8">
                    <span class="sr-only">Close</span>
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>

                  <div class="grid w-full grid-cols-1 items-start gap-y-8 gap-x-6 sm:grid-cols-12 lg:gap-x-8 lg:py-10">
                    {/* <div class="aspect-w-2 aspect-h-3 overflow-hidden rounded-lg bg-gray-100 sm:col-span-4 lg:col-span-5">
                      <img src="https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg" alt="Two each of gray, white, and black shirts arranged on table." class="object-cover object-center" />
                    </div> */}
                    {/* <div class="sm:col-span-12 lg:col-span-8">
                      <h2 class="text-7xl font-bold text-palette-500 sm:pr-12">
                        { selectedProject.name }
                      </h2>

                      {/* here goes the status of the proyect */}
                      {/* <div class="flex justify-start pt-5 pb-0">
                        <span class={`inline-block rounded-sm px-3 py-1 text-sm font-semibold mr-2 mb-2 `}
                        style={{ backgroundColor: selectedProject.status.color }}
                        >
                          {selectedProject.status.text}
                        </span>
                      </div>

                      <section aria-labelledby="information-heading" class="">
                        <h3 id="information-heading" class="sr-only">Proyects description</h3>
                        <div class="mt-8 space-y-6">
                          <p class="text-lg font-medium text-gray-900">
                            { selectedProject.description }
                          </p>
                        </div>
                        
                      </section>

                      {/* put links to github and the website if is deployed */}
                      {/* <div class="mt-12 flex flex-row justify-start ">
                        <a rel="noreferrer" href={selectedProject.github} target="_blank" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-palette-100 bg-gray-900 hover:bg-gray-700 hover:underline hover:cursor-pointer">
                          Go to Github repo 
                          <IoLogoGithub class="ml-2 h-5 w-5" aria-hidden="true" />
                        </a>

                        {
                          selectedProject.website || 
                          <a rel="noreferrer" href={selectedProject.website} target="_blank" class="ml-4 inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-palette-100 bg-gray-900 hover:bg-gray-700 hover:underline hover:cursor-pointer">
                            Website
                            <IoGlobe class="ml-2 h-5 w-5" aria-hidden="true" />
                          </a>
                        }
                      </div>

                    </div>
                    <div class="sm:col-span-12 lg:col-span-4 gap-y-2 flex flex-row flex-wrap justify-between">
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12">
                        Technologies
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            selectedProject.languages.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12">
                        Some libraries
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            selectedProject.libraries.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>
                      <div class="mt-0 space-y-1">
                      <h2 class="text-2xl font-bold text-gray-900 sm:pr-12">
                        Database and hosting
                      </h2>
                      <div class="mt-2 space-y-6">
                        <ul class="text-lg font-medium text-gray-900">
                          {
                            selectedProject.libraries.map( (tech, index) => (
                              <li key={index} class="flex flex-row items-center">
                                <IoCheckmarkCircleOutline class="h-5 w-5 text-palette-500" aria-hidden="true" />
                                <span class="ml-2">{tech}</span>
                              </li>
                            ))
                          }
                        </ul>
                      </div>
                      </div>

                    </div>



                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> */} 
   

        {/* Contact me */}
        <div class="flex flex-col w-full show-on-scroll">
          <div class="flex flex-col items-center justify-center px-5 mx-auto md:w-11/12 lg:px-10 md:flex-row py-20 border-t border-gray-700">
            <div class="basis-full flex items-center flex-row justify-center">
              <div class="relative flex justify-center items-center group cursor-pointer w-64 h-64 my-32 p-8 transition-color duration-[2s] hover:border-palette-400 border-gray-900 border-offset-[96px] "
               onMouseEnter={() => handleContactMe()} onMouseLeave={() => handleContactMeLeave()} onClick={() => handleCopyContact()}>
               {/* border-double border-y-4  */}
                <h2 class="text-7xl font-normal md:text-7xl text-center">
                  <button class="text-colored font-semibold ">
                    {
                      contactStatus === "copied" ? 
                        (<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-full h-full text-green-500">
                          <path strokeLinecap="round" strokeLinejoin="round" d="M11.35 3.836c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m8.9-4.414c.376.023.75.05 1.124.08 1.131.094 1.976 1.057 1.976 2.192V16.5A2.25 2.25 0 0118 18.75h-2.25m-7.5-10.5H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V18.75m-7.5-10.5h6.375c.621 0 1.125.504 1.125 1.125v9.375m-8.25-3l1.5 1.5 3-3.75" />
                        </svg>
                        )
                      :
                        contactStatus === "default" ? 
                          <IoChatboxEllipses className='transition-all group-hover:rotate-[360deg] duration-[1.5s] group-hover:text-palette-400 inline-block ' />
                        :
                          contactStatus === "email" ?
                            (<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-full h-full text-palette-400  ">
                              <path strokeLinecap="round" d="M16.5 12a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 10-2.636 6.364M16.5 12V8.25" />
                            </svg>)
                          :
                          (<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-full h-full text-palette-400  ">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 002.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 01-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 00-1.091-.852H4.5A2.25 2.25 0 002.25 4.5v2.25z" />
                          </svg>)
                    }



                  </button>
                </h2>
                <svg className='absolute top-0 left-0 w-full h-full scale-110 md:scale-150 transition-all duration-[1s] delay-150 group-hover:rotate-[360deg] group-hover:scale-150 md:group-hover:scale-[2.2] ' viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
                  <path fill="none" id="curve" d="M 50 100 A 50 50 0 1 1 150 100 A 50 50 0 1 1 50 100 " />
                  <text width="500">
                    <textPath alignment-baseline="top" href="#curve">
                    {
                      contactStatus === "default" ? 
                        "- CONTACT ME-CONTACT ME-CONTACT ME" 
                      : 
                        contactStatus === "copied" 
                        ? 
                          ("Copied to clipboard-Copied to clipboard" ).toUpperCase()
                        : 
                          contactStatus === "email" 
                            ? 
                            ("Click to copy email - Click to copy - ").toUpperCase()
                            :
                            ("Click to copy phone - Click to copy - ").toUpperCase()
                    }
                    
                    </textPath>
                  </text>
                </svg>
              </div>




            </div>
          </div>
        </div>
        
        {/* footer */}
        <div class="flex flex-col w-full bg-white">
          <div class="flex flex-col items-center justify-center px-5 mx-auto lg:w-11/12 lg:px-10 md:flex-row py-20 border-t border-gray-700">
            <div class="basis-full flex flex-col items-center justify-center lg:flex-grow md:flex md:flex-row md:justify-between gap-8 mx-auto">

            <div className="md:basis-1/3 text-gray-600 text-center">
              <p>
              © 2022 Juan Manuel Vila. All Rights Reserved.
              </p>
            </div>

            <div className="md:basis-1/3 text-gray-600 text-center">
              <p>
                512juanm@gmail.com
              </p>
            </div>

            <div className="md:basis-1/3 flex flex-row justify-center">
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Reddit">
                    <IoLogoGithub size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Facebook">
                    <IoLogoInstagram size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoLinkedin size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoDiscord size={25} />
                </a>
              </div>


            </div>
          </div>
        </div>



      </main>
    </div>
  )
}
