import Head from 'next/head'
import Image from 'next/future/image'

import Line from '../components/Line'
import LogoSVG from '../components/LogoSVG'
import LogoSVGsmall from '../components/LogoSVGsmall'

import { IoLogoJavascript, IoLogoNodejs, IoLogoGithub, IoLogoInstagram, IoLogoLinkedin, IoLogoReact, IoLogoDiscord, IoLogoHtml5, IoLogoCss3 } from 'react-icons/io5';
import { TbBrandNextjs } from 'react-icons/tb';
import { SiMysql, SiMongodb, SiJavascript } from 'react-icons/si';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smallLogoPortfolio.png" />
      </Head>

      <main className="w-full h-screen p-0 m-0">      

        <nav class="bg-white border-gray-200 px-3 md:px-20 md:py-12 rounded dark:bg-gray-900">
          <div class="container flex flex-wrap justify-between items-center mx-auto">
            <div class="md:flex md:justify-center md:w-auto md:order-2 mt-8 mx-2 md:mt-0">
              {/* <h1 class="md:basis-1/3 text-xl font-bold text-palette-400 font-mono text-center">Juan Manuel Vila</h1> */}
              <div class="md:basis-1/3 text-xl font-bold text-palette-400 font-mono text-center">
                <LogoSVG className="w-28 h-28 hidden md:block" />
                <LogoSVGsmall className="w-16 h-16 md:hidden" />
              </div>
            </div>
            <div class="md:basis-1/3 flex justify-center mt-6 lg:flex lg:mt-0 md:order-3">
              <div className="hidden md:flex">
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Reddit">
                    <IoLogoGithub size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Facebook">
                    <IoLogoInstagram size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoLinkedin size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoDiscord size={25} />
                </a>
              </div>
                <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
              </button>
            </div>
            <div class="md:basis-1/3 hidden justify-center mt-6 md:flex md:mt-0 lg:-mx-2 md:order-1" id="navbar-cta">
              <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold border-b-2 md:rounded-none border-palette-400 text-white bg-palette-400 rounded md:bg-transparent md:text-palette-400 md:p-0 dark:text-white" aria-current="page">Home</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <div class=" bg-white dark:bg-gray-900">
          <div class="flex flex-row items-center justify-center px-5 py-16 mx-auto lg:px-20 md:flex-row">
            
            <div class="basis-full md:basis-4/12 flex flex-col items-center justify-center text-center lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 md:items-start md:text-left md:flex md:flex-col md:justify-center">
              <h1 class="mb-4 text-2xl font-normal text-gray-900 lg:text-5xl md:text-3xl dark:text-white">Hi, I{"'"}m <span class="text-palette-400">John Doe</span></h1>
              {/* add a line svg */}
              <div class="w-16 h-1 mb-8 bg-palette-400 rounded-full md:mb-12"></div>
              <p class="mb-8 text-base font-normal text-gray-500 lg:text-lg md:text-base dark:text-gray-400">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              <div class="flex flex-row justify-center">
                <button class="px-8 py-2 text-base font-medium text-white transition-colors duration-200 transform bg-palette-400 rounded-md hover:bg-palette-500 focus:outline-none focus:bg-palette-500">Get Started</button>
                <button class="px-8 py-2 ml-4 text-base font-medium text-gray-700 transition-colors duration-200 transform bg-gray-100 rounded-md hover:bg-gray-200 focus:outline-none focus:bg-gray-200 dark:text-white dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:bg-gray-600">Learn More</button>
              </div>

            </div>
            <div class="basis-4/12 relative">
              <Image width="450" height="500" class="relative z-10 object-cover object-center" alt="hero" src="/heroIMG.jpg" 
                style={{
                  maskImage: "url(/about-me-main-image-mask.png)",
                  WebkitMaskImage: "url(/about-me-main-image-mask.png)",
                  maskRepeat: "no-repeat",
                  maskSize: "cover", 
                  WebkitMaskRepeat: "no-repeat",
                  WebkitMaskSize: "cover",
                  maskPosition: "center",
                  WebkitMaskPosition: "center",
                }}
              />
            </div>
            <div class="basis-4/12 relative flex flex-col items-center justify-center lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 md:items-start md:text-left md:flex md:flex-col md:justify-center">
                <div className='absolute -top-[2rem] left-0'>
                  <div className='relative'>
                  <SiJavascript className='relative text-yellow-400' />
                  {/* <h1 class=" mb-0 pl-8 text-right text-2xl font-normal text-gray-900 lg:text-5xl md:text-3xl dark:text-white">Hi, I{"'"}m <span class="text-palette-400">John</span></h1> */}
                  <Line className="absolute -translate-y-[70px] -translate-x-[20%]" />
                  </div>
                </div>
                <div className='absolute -top-[8rem] left-0'>
                  <div className='relative'>
                  <h1 class=" mb-0 pl-8 text-right text-2xl font-normal text-gray-900 lg:text-5xl md:text-3xl dark:text-white">Hi, I{"'"}m <span class="text-palette-400">John</span></h1>
                  <Line className="absolute -translate-y-[70px] -translate-x-[20%]" />
                  </div>
                </div>
                <div className='absolute top-[4rem] left-0'>
                  <div className='relative'>
                  <h1 class=" mb-0 pl-8 text-right text-2xl font-normal text-gray-900 lg:text-5xl md:text-3xl dark:text-white">Hi, I{"'"}m <span class="text-palette-400">John</span></h1>
                  <Line className="absolute -translate-y-[70px] -translate-x-[20%]" />
                  </div>
                </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
