import Head from 'next/head'
import Image from 'next/future/image'

import data from '../data.json'

import LogoSVG from '../components/LogoSVG'
import LogoSVGsmall from '../components/LogoSVGsmall'

import { IoLogoJavascript, IoLogoNodejs, IoLogoGithub, IoLogoInstagram, IoLogoLinkedin, IoLogoReact, IoLogoDiscord, IoLogoHtml5, IoLogoCss3 } from 'react-icons/io5';
import { SiMongodb, SiNextdotjs } from 'react-icons/si';
import { GrMysql } from 'react-icons/gr';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smallLogoPortfolio.png" />
      </Head>

      <main className="w-full h-screen p-0 m-0">      

        <nav class="bg-white border-gray-200 px-3 md:px-20 md:py-8 rounded dark:bg-gray-900">
          <div class="container flex flex-wrap justify-between items-center mx-auto">
            <div class="md:flex md:justify-center md:w-auto md:order-2 mt-8 mx-2 md:mt-0">
              {/* <h1 class="md:basis-1/3 text-xl font-bold text-palette-400 font-mono text-center">Juan Manuel Vila</h1> */}
              <div class="md:basis-1/3 text-xl font-bold text-palette-400 font-mono text-center">
                <LogoSVG className="w-28 h-28 hidden md:block" />
                <LogoSVGsmall className="w-16 h-16 md:hidden" />
              </div>
            </div>
            <div class="md:basis-1/3 flex justify-center mt-6 lg:flex lg:mt-0 md:order-3">
              <div className="hidden md:flex">
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Reddit">
                    <IoLogoGithub size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Facebook">
                    <IoLogoInstagram size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoLinkedin size={25} />
                </a>
                <a href="#" class="mx-2 text-gray-600 transition-colors duration-300 transform dark:text-palette-300 hover:text-palette-300 dark:hover:text-palette-300" aria-label="Twitter">
                    <IoLogoDiscord size={25} />
                </a>
              </div>
                <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
              </button>
            </div>
            <div class="md:basis-1/3 hidden justify-center mt-6 md:flex md:mt-0 lg:-mx-2 md:order-1" id="navbar-cta">
              <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold border-b-2 md:rounded-none border-palette-400 text-white bg-palette-400 rounded md:bg-transparent md:text-palette-400 md:p-0 dark:text-white" aria-current="page">Home</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pr-4 pl-3 font-bold text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-palette-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>




          <div class="flex flex-col items-center justify-center px-5 py-16 mx-auto lg:px-20 md:flex-row">
              <h1 class="mb-4 text-2xl text-gray-900 lg:text-6xl md:text-3xl text-center font-normal ">
                Hi, I{"'"}m <span class="text-palette-400">Juan Manuel Vila</span> <br class="hidden md:block" /><span class="text-palette-400">Full Stack Developer</span> <br class="hidden md:block" />from <span class="text-palette-400">Argentina</span>
              </h1>
          </div>



        <div class=" bg-white dark:bg-gray-900">
          <div class="flex flex-col items-center justify-center px-5 py-16 mx-auto lg:px-20 md:flex-row">
            
            <div class="basis-full md:basis-4/12 flex flex-col items-center justify-center text-center lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 md:items-start md:text-left md:flex md:flex-col md:justify-center">
              
              <div class="flex flex-col">
                <h4 class="mb-3 text-sm font-normal text-gray-900 uppercase"><span class="border-b-2 border-palette-400 text-palette-300">Biography</span></h4>
                <p class="mb-12 text-base font-normal text-gray-700 md:text-md font-amiri">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed ex ea commodo consequat.
                </p>
              </div>
              <div class="flex flex-col">
                <h4 class="mb-3 text-sm font-normal text-gray-900 uppercase"><span class="border-b-2 border-palette-400 text-palette-300">Contact</span></h4>
                <p class="mb-12 text-base font-normal text-gray-700 md:text-md font-amiri">
                  512juamn@gmail.com <br />
                  +54 9 2346-570764 <br />
                  La Plata, Buenos Aires, Argentina

                </p>
              </div>

              
            </div>

            {/* IMAGE */}
            <div class="basis-4/12 relative p-4 w-64 md:w-full">
              <Image width="500" height="500" class="relative mx-auto z-10 object-cover object-center" alt="hero" src="/heroIMG.jpg"
                style={
                  {
                    'border-top-left-radius': "12rem 12rem",
                    'border-top-right-radius': "12rem 12rem",
                    'border-bottom-right-radius': "12rem 12rem",
                    'border-bottom-left-radius': "12rem 12rem",
                    border: "10px solid #fefefe",
                    boxShadow: "0.1px 0.1px 1px 0.5px rgba(18, 164, 42, 0.9), -0.1px -0.1px 1px 0.5px rgba(18, 164, 42, 0.9)",
                  }
                }
                // style={{
                //   maskImage: "url(/about-me-main-image-mask.png)",
                //   WebkitMaskImage: "url(/about-me-main-image-mask.png)",
                //   maskRepeat: "no-repeat",
                //   maskSize: "cover", 
                //   WebkitMaskRepeat: "no-repeat",
                //   WebkitMaskSize: "cover",
                //   maskPosition: "center",
                //   WebkitMaskPosition: "center",
                // }}
              />
            </div>

            {/* LANGUAGES */}
            <div class="basis-4/12 relative flex flex-col items-center justify-center lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 md:items-start md:text-left md:flex md:flex-col md:justify-center">
              <h1 class="mb-2 text-xl font-normal text-gray-900 lg:text-3xl md:text-2xl dark:text-white border-b-2 border-palette-400">My Skills</h1>

            </div>

          </div>

        </div>
{/* https://moonex.ibthemespro.com/home-freelancer */}
        <div class="flex flex-col w-full bg-white">
          <div class="flex flex-col items-center justify-center px-5 mx-auto lg:w-11/12 lg:px-10 md:flex-row py-20 border-y border-gray-700">
            <div class="basis-full flex flex-col items-center justify-center text-center lg:flex-grow md:flex md:flex-col md:justify-center">
              <h1 class="my-4 text-xl font-normal text-gray-900 md:text-4xl dark:text-white border-b-2 border-palette-400">My Knowledge</h1>
              {/* list of languajes */}
              <div class="flex flex-row justify-center gap-8 flex-wrap py-20">

                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                    <IoLogoHtml5 size={45} color="#3178C6" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                    <p class="text-base font-semibold group-hover:text-[#3178C6] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">HTML</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoCss3 size={45} color="#264DE4" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#264DE4] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">CSS</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoJavascript size={45} color="#F7DF1E" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#F7DF1E] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">Javascript</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoReact size={45} color="#61DAFB" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#61DAFB] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">React</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <IoLogoNodejs size={45} color="#339933" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#339933] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">NodeJS</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <SiNextdotjs size={45} color="#3776AB" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#3776AB] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">NextJS</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <GrMysql size={45} color="#4479A1" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#4479A1] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">MySQL</p>
                  </div>
                </div>
                <div class="flex flex-col items-center justify-center gap-0">
                  <div className='group flex flex-col items-center justify-center gap-2 w-32 h-48 bg-gray-200 grayscale hover:grayscale-0 rounded-[9.375rem]' style={{padding:"3.4375rem .9375rem 2.8125rem"}}>
                  <SiMongodb size={45} color="#47A248" className='transition-all duration-500 group-hover:-translate-y-[20%] group-hover:scale-110 ' />
                  <p class="text-base font-semibold group-hover:text-[#47A248] text-gray-500 lg:text-lg md:text-base dark:text-gray-450">MongoDB</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="flex flex-col w-full py-20 bg-gray-50 dark:bg-gray-800">
          <div class="flex flex-col items-center justify-center w-full py-20 bg-gray-50 dark:bg-gray-800">
            <h1 class="mb-2 text-xl font-normal text-gray-900 lg:text-3xl md:text-2xl dark:text-white">My Projects</h1>
            {/* add a line svg */}
            <div class="w-24 h-0.5 mb-8 bg-palette-400 rounded-full md:mb-12"></div>
            <div class="flex flex-col md:flex-row justify-start gap-8 flex-wrap py-2">
              {/* create cards for each proyect */}
              {
                data.proyects.map( (proyect, index) => (
                  <div key={index} class="basis-1/3 m-12 md:m-0 group block overflow-hidden rounded-2xl hover:shadow-md hover:scale-110 border border-gray-900 transition-all duration-500 ease-out">
                    <Image
                      width={500}
                      height={500}
                      alt="Office"
                      src="/donateloImg.png"
                      class="object-cover w-full h-56 md:h-64 lg:h-80"
                    />

                    <div class="p-4 bg-gray-200 shadow-2xl ">
                      <a href='#' class="text-xs text-gray-500 hover:underline m-0">website.com</a>

                      <h5 class="text-sm text-white">
                        How to position your furniture for positivity
                      </h5>

                      <p class="mt-1 text-xs text-gray-500">
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum nobis
                        aliquid accusamus? Sint, sequi voluptas.
                      </p>

                      <div class="flex flex-row items-center justify-center gap-0 flex-wrap py-2 group-hover:gap-4 transition-all transition-400">
                        <div class="flex flex-col items-center justify-center gap-0">
                          <IoLogoHtml5 size={40} color="#3178C6" />
                          <p class="text-base font-semibold group-hover:text-palette-[] text-gray-500 lg:text-xs md:text-base dark:text-gray-400">HTML</p>
                        </div>
                        <div class="flex flex-col items-center justify-center gap-0">
                          <IoLogoCss3 size={40} color="#264DE4" />
                          <p class="text-base font-semibold group-hover:text-palette-[] text-gray-500 lg:text-xs md:text-base dark:text-gray-400">CSS</p>
                        </div>
                      </div>
                    </div>
                  </div>

                  
                ))
              }

            </div>
          </div>
        </div>

      </main>
    </div>
  )
}
