import "@/styles/globals.css"
import localFont from "next/font/local"
import { NextIntlClientProvider, useMessages } from "next-intl"

import Header from "@/components/Header"

const myFont = localFont({
  src: "../../../styles/Kode_Mono/KodeMono-VariableFont_wght.ttf",
  display: "auto",
  variable: "--font-kode"
})

export const metadata = {
  title: "Juan Manuel Vila - Portfolio",
  description: "Generated by create next app"
}

export default function LocaleLayout({ children, params: { locale } }) {
  const messages = useMessages()
  return (
    <html
      lang={locale}
      className={`${myFont.variable}`}
    >
      <body className="relative font-kode w-full min-h-screen p-0 m-0 overflow-x-hidden">
        <NextIntlClientProvider messages={messages}>
          <Header lang={locale} />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
